### ISSUE TITLE
Ballerina active distribution is not set properly

### ISSUE THREAD

**Issue by RakhithaRR** [ballerina-platform/ballerina-update-tool#170] opened 2021-07-06 03:35 UTC
**Description:**
The following commands do not set the ballerina active distribution properly.
`sudo bal dist pull slalpha1`
`sudo bal dist use slalpha1`

`sudo bal version` command returns the following output.
```
Ballerina Swan Lake Beta 1
Language specification 2021R1
Update Tool 1.3.5
```
Also, I can't use `bal` commands without `sudo`. Running commands without sudo gives `permission denied: bal` error.

![image](https://user-images.githubusercontent.com/25485273/124538309-07c84680-de39-11eb-840c-c9a4b098edac.png)

**Steps to Reproduce**
Download Ballerina Swan Lake Beta 1 (linux deb) from https://ballerina.io/downloads/ and install.

**Affected Versions:**
Ballerina Swan Lake Beta 1

**OS, DB, other environment details and versions:**
Ubuntu 20.04.2

**Comment by RakhithaRR** [comment] 2021-07-06 07:28
Changing the permissions of the ballerina executable solved this issue for me for the time being 
`chmod 755 /usr/lib/ballerina/bin/bal`

But it seems the default installation process does not give required permissions for the none-root users

**Comment by NipunaMadhushan** [comment] 2021-08-12 09:09
I have tested with several ubuntu machines but the above was not occurred in any of them. We should give the permission only for writing the files in /usr/lib/ballerina file directory. otherwise `sudo` command is not required.

**Comment by keizer619** [comment] 2021-12-01 05:55
Since this is not reproducible i will be closing the issue. If there are any concerns please feel free to reopen

**Closed by keizer619** 2021-12-01 05:55 UTC
Labels: Type/Bug
