### ISSUE TITLE
[Windows] Unexpected error message when we run bal dist pull <unavailable distribution> command

### ISSUE THREAD

**Issue by NipunaMadhushan** [ballerina-platform/ballerina-update-tool#198] opened 2022-01-13 07:18 UTC
Label: High Priority

**Description:**
Unexpected error message occurs when we run the `bal dist pull <unavailable distribution>` command.

```
Fetching the 'slbeta7' distribution from the remote server...
ballerina: distribution 'slbeta7' not found
'N_BALLERINA" == "true" (' is not recognized as an internal or external command,
operable program or batch file.
ballerina: unknown command 'dist'
Run 'bal help' for usage.
```

**Steps to reproduce:**
Run the following command on windows.
`bal dist pull <unavailable distribution>`

eg : `bal dist pull slbeta7`

**Affected Versions:**
All update tool versions

**Comment by udda1996** [comment] 2022-08-19 07:55
This is a duplicate of #233

**Closed** 2022-08-19 07:56 UTC
Labels: Type/Bug, Reason/Other
